# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GeneratorTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1079, 780)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1061, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_SearchWord = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SearchWord.setGeometry(QtCore.QRect(10, 10, 331, 21))
        self.lineEdit_SearchWord.setInputMask("")
        self.lineEdit_SearchWord.setText("")
        self.lineEdit_SearchWord.setClearButtonEnabled(False)
        self.lineEdit_SearchWord.setObjectName("lineEdit_SearchWord")
        self.pushButton_SearchWord = QtWidgets.QPushButton(self.tab)
        self.pushButton_SearchWord.setGeometry(QtCore.QRect(350, 10, 71, 23))
        self.pushButton_SearchWord.setObjectName("pushButton_SearchWord")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 150, 411, 581))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_WordEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_WordEdit.setGeometry(QtCore.QRect(100, 20, 301, 20))
        self.lineEdit_WordEdit.setObjectName("lineEdit_WordEdit")
        self.label_Word = QtWidgets.QLabel(self.groupBox)
        self.label_Word.setGeometry(QtCore.QRect(10, 20, 47, 21))
        self.label_Word.setObjectName("label_Word")
        self.lineEdit_PartofSpeech = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_PartofSpeech.setGeometry(QtCore.QRect(100, 50, 301, 20))
        self.lineEdit_PartofSpeech.setText("")
        self.lineEdit_PartofSpeech.setObjectName("lineEdit_PartofSpeech")
        self.label_PartofSpeech = QtWidgets.QLabel(self.groupBox)
        self.label_PartofSpeech.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.label_PartofSpeech.setObjectName("label_PartofSpeech")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 90, 191, 51))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_PhoneticSymbolUS = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_PhoneticSymbolUS.setGeometry(QtCore.QRect(10, 20, 113, 21))
        self.lineEdit_PhoneticSymbolUS.setText("")
        self.lineEdit_PhoneticSymbolUS.setObjectName("lineEdit_PhoneticSymbolUS")
        self.pushButton_SoundUS = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_SoundUS.setGeometry(QtCore.QRect(130, 20, 51, 21))
        self.pushButton_SoundUS.setObjectName("pushButton_SoundUS")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 90, 191, 51))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_PhoneticSymbolUK = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_PhoneticSymbolUK.setGeometry(QtCore.QRect(10, 20, 113, 21))
        self.lineEdit_PhoneticSymbolUK.setText("")
        self.lineEdit_PhoneticSymbolUK.setObjectName("lineEdit_PhoneticSymbolUK")
        self.pushButton_SoundUK = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_SoundUK.setGeometry(QtCore.QRect(130, 20, 51, 23))
        self.pushButton_SoundUK.setObjectName("pushButton_SoundUK")
        self.label_Definition = QtWidgets.QLabel(self.groupBox)
        self.label_Definition.setGeometry(QtCore.QRect(10, 150, 391, 21))
        self.label_Definition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Definition.setObjectName("label_Definition")
        self.plainTextEdit_DefinitionSingle = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_DefinitionSingle.setGeometry(QtCore.QRect(10, 180, 391, 61))
        self.plainTextEdit_DefinitionSingle.setPlainText("")
        self.plainTextEdit_DefinitionSingle.setObjectName("plainTextEdit_DefinitionSingle")
        self.plainTextEdit_example = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_example.setGeometry(QtCore.QRect(10, 280, 391, 141))
        self.plainTextEdit_example.setObjectName("plainTextEdit_example")
        self.label_Example = QtWidgets.QLabel(self.groupBox)
        self.label_Example.setGeometry(QtCore.QRect(10, 250, 391, 21))
        self.label_Example.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Example.setObjectName("label_Example")
        self.label_Synonym = QtWidgets.QLabel(self.groupBox)
        self.label_Synonym.setGeometry(QtCore.QRect(10, 430, 391, 21))
        self.label_Synonym.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Synonym.setObjectName("label_Synonym")
        self.plainTextEdit_synonym = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_synonym.setGeometry(QtCore.QRect(10, 460, 391, 71))
        self.plainTextEdit_synonym.setObjectName("plainTextEdit_synonym")
        self.pushButton_AddCard = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_AddCard.setGeometry(QtCore.QRect(10, 550, 75, 23))
        self.pushButton_AddCard.setObjectName("pushButton_AddCard")
        self.pushButton_Cancel = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(100, 550, 75, 23))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.listWidget_DefinitionList = QtWidgets.QListWidget(self.tab)
        self.listWidget_DefinitionList.setGeometry(QtCore.QRect(10, 40, 411, 101))
        self.listWidget_DefinitionList.setObjectName("listWidget_DefinitionList")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(440, 10, 601, 681))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_GoogleImage1 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage1.setGeometry(QtCore.QRect(20, 30, 181, 151))
        self.label_GoogleImage1.setAutoFillBackground(False)
        self.label_GoogleImage1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage1.setText("")
        self.label_GoogleImage1.setObjectName("label_GoogleImage1")
        self.label_GoogleImage2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage2.setGeometry(QtCore.QRect(210, 30, 181, 151))
        self.label_GoogleImage2.setAutoFillBackground(False)
        self.label_GoogleImage2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage2.setText("")
        self.label_GoogleImage2.setObjectName("label_GoogleImage2")
        self.label_GoogleImage3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage3.setGeometry(QtCore.QRect(400, 30, 181, 151))
        self.label_GoogleImage3.setAutoFillBackground(False)
        self.label_GoogleImage3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage3.setText("")
        self.label_GoogleImage3.setObjectName("label_GoogleImage3")
        self.label_GoogleImage4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage4.setGeometry(QtCore.QRect(20, 190, 181, 151))
        self.label_GoogleImage4.setAutoFillBackground(False)
        self.label_GoogleImage4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage4.setText("")
        self.label_GoogleImage4.setObjectName("label_GoogleImage4")
        self.label_GoogleImage5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage5.setGeometry(QtCore.QRect(210, 190, 181, 151))
        self.label_GoogleImage5.setAutoFillBackground(False)
        self.label_GoogleImage5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage5.setText("")
        self.label_GoogleImage5.setObjectName("label_GoogleImage5")
        self.label_GoogleImage6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage6.setGeometry(QtCore.QRect(400, 190, 181, 151))
        self.label_GoogleImage6.setAutoFillBackground(False)
        self.label_GoogleImage6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage6.setText("")
        self.label_GoogleImage6.setObjectName("label_GoogleImage6")
        self.label_GoogleImage7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage7.setGeometry(QtCore.QRect(20, 350, 181, 151))
        self.label_GoogleImage7.setAutoFillBackground(False)
        self.label_GoogleImage7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage7.setText("")
        self.label_GoogleImage7.setObjectName("label_GoogleImage7")
        self.label_GoogleImage8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage8.setGeometry(QtCore.QRect(210, 350, 181, 151))
        self.label_GoogleImage8.setAutoFillBackground(False)
        self.label_GoogleImage8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage8.setText("")
        self.label_GoogleImage8.setObjectName("label_GoogleImage8")
        self.label_GoogleImage9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage9.setGeometry(QtCore.QRect(400, 350, 181, 151))
        self.label_GoogleImage9.setAutoFillBackground(False)
        self.label_GoogleImage9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage9.setText("")
        self.label_GoogleImage9.setObjectName("label_GoogleImage9")
        self.label_GoogleImage10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage10.setGeometry(QtCore.QRect(20, 510, 181, 151))
        self.label_GoogleImage10.setAutoFillBackground(False)
        self.label_GoogleImage10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage10.setText("")
        self.label_GoogleImage10.setObjectName("label_GoogleImage10")
        self.label_GoogleImage11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage11.setGeometry(QtCore.QRect(210, 510, 181, 151))
        self.label_GoogleImage11.setAutoFillBackground(False)
        self.label_GoogleImage11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage11.setText("")
        self.label_GoogleImage11.setObjectName("label_GoogleImage11")
        self.label_GoogleImage12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_GoogleImage12.setGeometry(QtCore.QRect(400, 510, 181, 151))
        self.label_GoogleImage12.setAutoFillBackground(False)
        self.label_GoogleImage12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_GoogleImage12.setText("")
        self.label_GoogleImage12.setObjectName("label_GoogleImage12")
        self.label_Status = QtWidgets.QLabel(self.tab)
        self.label_Status.setGeometry(QtCore.QRect(440, 700, 601, 21))
        self.label_Status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Status.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.label_Status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Status.setObjectName("label_Status")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AnkiCardGenerator"))
        self.lineEdit_SearchWord.setPlaceholderText(_translate("Dialog", "Input word here"))
        self.pushButton_SearchWord.setText(_translate("Dialog", "Search"))
        self.groupBox.setTitle(_translate("Dialog", "Content"))
        self.label_Word.setText(_translate("Dialog", "Word"))
        self.label_PartofSpeech.setText(_translate("Dialog", "Part of speech"))
        self.groupBox_2.setTitle(_translate("Dialog", "US"))
        self.pushButton_SoundUS.setText(_translate("Dialog", "Play"))
        self.groupBox_3.setTitle(_translate("Dialog", "UK"))
        self.pushButton_SoundUK.setText(_translate("Dialog", "Play"))
        self.label_Definition.setText(_translate("Dialog", "Definition"))
        self.label_Example.setText(_translate("Dialog", "Example"))
        self.label_Synonym.setText(_translate("Dialog", "Synonym"))
        self.pushButton_AddCard.setText(_translate("Dialog", "Add Card"))
        self.pushButton_Cancel.setText(_translate("Dialog", "Cancel"))
        self.groupBox_4.setTitle(_translate("Dialog", "Google images"))
        self.label_Status.setText(_translate("Dialog", "Ready ! Please input word to search bar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "InputCard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
